In [8]:
import os
import sys
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

# Automatically reload imported programmes
%load_ext autoreload
%autoreload 2

# Directories (ammend as necessary)
root_dir = '/content/gdrive/MyDrive/IDSAI/PROOF/filament-segmentation'
os.chdir(root_dir)  # Move to root_dir
sys.path.insert(0, root_dir)

masks_path = os.path.join(root_dir, 'data/masks-tf1/semantic/*.png')


Mounted at /content/gdrive
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
!ls

autoencoder.ipynb  data_processing.ipynb  requirements.txt
checkpoints	   get_line_endings.py	  unmasking.ipynb
data		   README.md		  utils


In [21]:
import glob
import numpy as np
from skimage import io
from utils import get_line_ends

masks = []
mask_names = glob.glob(masks_path)
for mask_file in mask_names:
    mask = io.imread(mask_file)
    masks.append(mask[:, :, 0])


In [26]:
import numpy as np

In [31]:
mp = os.path.join(root_dir, 'data/masks-tf1/instance/tf1_001/tf1_001_32.png')
#mp = os.path.join(root_dir, 'data/masks-tf1/semantic/tf1_001.png')
m = io.imread(mask_file)
m = m[:, :, 0]
get_line_ends(m, dpi=72)


IndexError: ignored

In [29]:
np.where(mask)

(array([ 212,  212,  212, ..., 3702, 3702, 3702]),
 array([3674, 3674, 3674, ...,  367,  367,  367]),
 array([0, 1, 2, ..., 0, 1, 2]))

In [22]:
get_line_ends(masks[0], dpi=72)


IndexError: ignored

In [ ]:
# Install requirements 
!pip install -r requirements.txt
# %tensorflow_version 1.x
import h5py, keras
import tensorflow as tf
print('h5py version: ', h5py.__version__)  # Require version <3.0
print('keras version: ', keras.__version__)  # Suggested version 2.2.5
print('tensorflow version: ', tf.__version__)  # Look for version <2.0